#!/usr/bin/env python3
"""
Inject WKCD map config from repo-root .env into map/wkcd-trees.html.

Usage:
    python sync_wkcd_config.py

Edit GITHUB_OWNER, GITHUB_REPO, and GITHUB_COMMIT in .env, then run this script.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
ENV_FILE = REPO_ROOT / ".env"
HTML_PATH = REPO_ROOT / "map" / "wkcd-trees.html"

CONFIG_START = "// WKCD_CONFIG_START"
CONFIG_END = "// WKCD_CONFIG_END"


def load_dotenv(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        values[key.strip()] = value.strip().strip("\"'")
    return values


def get_github_raw_base(env: dict[str, str]) -> str:
    owner = env.get("GITHUB_OWNER", "").strip()
    repo = env.get("GITHUB_REPO", "").strip()
    commit = env.get("GITHUB_COMMIT", "").strip()
    if not owner or not repo or not commit:
        print(
            "Error: GITHUB_OWNER, GITHUB_REPO, and GITHUB_COMMIT must be set in .env\n"
            f"  {ENV_FILE}"
        )
        sys.exit(1)
    return f"https://raw.githubusercontent.com/{owner}/{repo}/{commit}/map"


def build_config_block(env: dict[str, str]) -> str:
    github_raw_base = get_github_raw_base(env)
    delivery_hash = env.get("CLOUDFLARE_IMAGE_DELIVERY_HASH", "w8B9Irt4MxIF11C23YczhQ").strip()
    thumb_variant = env.get("CLOUDFLARE_IMAGE_VARIANT_THUMBNAIL", "H300").strip()
    full_variant = env.get("CLOUDFLARE_IMAGE_VARIANT_FULL", "public").strip()

    return f"""{CONFIG_START} — generated by map/~python/sync_wkcd_config.py; edit .env instead
        const GITHUB_RAW_BASE = '{github_raw_base}';
        const CLOUDFLARE_IMAGE_DELIVERY_URL = 'https://imagedelivery.net/{delivery_hash}';
        const CLOUDFLARE_IMAGE_VARIANT_THUMBNAIL = '{thumb_variant}';
        const CLOUDFLARE_IMAGE_VARIANT_FULL = '{full_variant}';
        {CONFIG_END}"""


def main() -> None:
    env = load_dotenv(ENV_FILE)
    html = HTML_PATH.read_text(encoding="utf-8")
    config_block = build_config_block(env)

    pattern = re.compile(
        rf"{re.escape(CONFIG_START)}.*?{re.escape(CONFIG_END)}",
        re.DOTALL,
    )
    if not pattern.search(html):
        print(f"Error: config markers not found in {HTML_PATH}")
        sys.exit(1)

    updated = pattern.sub(config_block, html, count=1)
    HTML_PATH.write_text(updated, encoding="utf-8")
    print(f"Updated {HTML_PATH.name} from {ENV_FILE.name}")
    print(f"  GITHUB_RAW_BASE = {get_github_raw_base(env)}")


if __name__ == "__main__":
    main()
